name: Run benchmarks

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        benchmark:
          - bio
          - nlp
          - file-enc
          - unix50
          - log-analysis
          - max-temp
          - media-conv
          - sklearn
          - covid-mts
          - riker
          - oneliners
          - vps-audit
          - makeself

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the image you built
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker tag \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            benchmark-env

      - name: Set execute permissions for main.sh
        run: chmod +x main.sh

      - name: Run Benchmark ${{ matrix.benchmark }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/benchmarks \
            -w /benchmarks \
            benchmark-env \
            bash -c "./main.sh ${{ matrix.benchmark }} --min"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.benchmark }}-logs
          path: ${{ matrix.benchmark }}/${{ matrix.benchmark }}.*
          if-no-files-found: error
